name: 'Website Pull Deployment'
description: 'Deploy your website using pull-based-deployment'

inputs:
  target-dir:
    description: 'Directory containing content to sync'
    required: false
    default: 'dist'
  deployment-id:
    description: 'Id of the deployment'
    required: true
  deployment-secret:
    description: 'Secret of the deployment'
    required: true
  webhook-url:
    description: 'Url of the webhook remote'
    required: true

runs:
  using: composite
  steps:
    - name: Push Temp Branch
      id: push-temp-branch
      shell: bash
      env:
        TARGET_DIR: ${{ inputs.target-dir }}
        RUN_ID: ${{ github.run_id }}
        RUN_ATTEMPT: ${{ github.run_attempt }}
      run: |
        repo_root=$(git rev-parse --show-toplevel)
        mv "$TARGET_DIR" "${repo_root}/.temp-deployment"
        
        git config --global user.name 'Pull Deployment Action' 
        git config --global user.email 'private@glitchdev.me'
        
        branch_name="TEMP-DEPLOYMENT-${RUN_ID}-${RUN_ATTEMPT}"
        git checkout --orphan "${branch_name}"
        
        git reset
        git add -f "${repo_root}/.temp-deployment"
        git commit -m "chore: create temporary deployment branch" | head -n2
        git push origin "${branch_name}"
        
        echo "branch-name=${branch_name}" >> $GITHUB_OUTPUT
        echo "commit-sha=$(git rev-parse @)" >> $GITHUB_OUTPUT

    - name: Trigger Pull Deployment
      shell: bash
      env:
        DEPLOYMENT_ID: ${{ inputs.deployment-id }}
        DEPLOYMENT_SECRET: ${{ inputs.deployment-secret }}
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        BRANCH_NAME: ${{ steps.push-temp-branch.outputs.branch-name }}
        COMMIT_SHA: ${{ steps.push-temp-branch.outputs.commit-sha }}
      run: |
        response=$(curl -X PUT \
          -s -w "\n${http_code}" \
          -H "Content-Type: application/json" \
          -d '{ \
            "deploymentId": "${DEPLOYMENT_ID}", \
            "deploymentSecret": "${DEPLOYMENT_SECRET}" \
            "branchName": "${BRANCH_NAME}" \
            "commitSha": "${COMMIT_SHA}" \
          }' "${WEBHOOK_URL}/deploy-website")
    
        response_code=$(tail -n1 <<< "$response")
        response_content=$(sed '$ d' <<< "$response")

        if [[ response_code == "200" ]]; then
          echo "Successfully deployed website"
          echo "$response_content"
        else
          echo "::error::Failed to deploy website with status code: $response_code"
          echo "$response_content"
          exit 1
        fi
    - name: Cleanup Temp Branch
      shell: bash
      if: ${{ always() && steps.push-temp-branch.conclusion == 'success' }}
      env:
        BRANCH_NAME: ${{ steps.push-temp-branch.outputs.branch-name }}
      run: |
        git checkout main -f
        git branch -D "${BRANCH_NAME}"
        git push origin --delete "${BRANCH_NAME}"
      
